### PR TITLE
Remove delegation from Sensu service handlers

### PR DESCRIPTION
**Pull request by danielkza**
Delegating tasks to `sensu_api_host` assumes some particular conditions,
such as there only being one API host, and that the value represents a
hostname under Ansible control, instead of load balancer address.

Remove it completely, as any masters under management should have their
services properly restarted when they reach the same tasks in their own
plays.

### CODE REVIEW

**Comment by danielkza** [comment]
I've just tested a bit more today and it seems the current situation with services is unreliable even with a single machine. For example, an API restart should be triggered when the transport configuration changes, but it is not. Also, the Redis configuration is written two times, once in the client and server tasks. It seems wise to split those up into a set of common tasks.

**Comment by smuth4** [comment]
Dumb question: is there any reason common.yml and client.yml can't be combined? (of course client.yml would have to be moved up to where common.yml is now) Either way, thanks for taking the time to improve the PR, it handles one or two other gotchas I found as well. Since it touches a lot of things I'll want to do one more test cycle, but I like how it looks 👍

**Comment by danielkza** [comment]
@smuth4 I do think they can be combined, I didn't do it to avoid changing the structure even more than I already did.

I only had the chance to test with Ubuntu, but it is indeed a good idea to check if FreeBSD and SmartOS really needed those tasks in their particular places.

**Comment by smuth4** [comment]
Thanks for following up, that also solves one or two other gotchas I found. Since it touches a lot of things I'll want to bring it through one more test cycle, but I like the way it's looking 👍

**Comment by smuth4** [comment]
Sorry, didn't mean to let this molder. Thanks for the work!

**Pull request merged**
