### PR TITLE
Add TravisCI tests #114

### PR DESCRIPTION
**Pull request by jaredledvina**
Attempting to get TravisCI builds to work, this PR _might_ do it. 

Uses https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/ which I've used with lots of success in the past. It's not perfect yet by a long shot.

### CODE REVIEW

**Comment by jaredledvina** [comment]
Booyah! That started the Travis build, now to see how many failures I get.

**Comment by mbbroberg** [comment]
git_commit_2x

**Comment by mbbroberg** [comment]
But seriously, anything we can help you with @jaredledvina? cc @cjchand

**Comment by jaredledvina** [comment]
haha that picture is the best! At this point, it's mostly on me to iterate here to get a working Travis build. That and finding some time to do that. Luckily, the holidays should present me with plenty of down time to hammer on this.

**Comment by cjchand** [comment]
@plantir On a related note, been meaning to reach out. Please don’t feel this is all on you. Maybe we need a Slack/Zoom/Whatevs early next week to lay down plans and divvy up some work. Love the leadership!

**Comment by cjchand** [comment]
Damned auto-co-wreck. Sorry, @palantir.

**Comment by jaredledvina** [comment]
Hey @cjchand, sure thing! Let's sync up on slack in the near future and lay out some of the work. Also, it's @jaredledvina (I do work for Palantir though :) )

**Comment by cjchand** [comment]
Well, that’s what I get for trying to reply via phone while at a company function. Will stick to laptop, working hours only from here on out. (Sorry)^2 ;)

**Comment by jaredledvina** [comment]
I'm so very close here, remaining issues w/ the TravisCI builds:
* Ubuntu 16.04 - For some reason isn't getting the core `ansible_default_ipv4` fact, appears to be due to Ansible not finding a default IPv4 route inside the container. 
* CentOS 6 - When executing `Ensure Sensu RabbitMQ user has access to the Sensu vhost`, RabbitMQ appears to be down 
* Ubuntu 12.04 - Unable to install RabbitMQ, perhaps we drop tested support for 12.04, I believe it's old enough now to warrant that. 

Other than that, CentOS 7, Ubuntu 14.04, Debian 8, and Debian 9 are all successfully deploying this role and on a second run passing the idempotence test.

**Comment by jaredledvina** [comment]
Ah, looks like even RabbitMQ states they don't support Ubuntu 12.04, https://www.rabbitmq.com/install-debian.html, dropped it.

**Comment by jaredledvina** [comment]
https://github.com/geerlingguy/docker-ubuntu1604-ansible/pull/6 fixes the issue with the Ubuntu 16.04 failures.

**Comment by jaredledvina** [comment]
My god, the tests, they **finally** pass!

**Comment by jaredledvina** [comment]
Superceeded by https://github.com/sensu/sensu-ansible/pull/129

**Pull request closed without merging**
