### PR TITLE
Updates playbook to 2.5-2.7

### PR DESCRIPTION
**Pull request by michaelpporter**
After rewing chagns listed in #156 all playbooks should be to 2.5 and beyond.

### CODE REVIEW

**Review by jaredledvina — APPROVED** [review]
Woooooo, thanks @michaelpporter! I really appreciate all the help with this PR's, this one looks good! 
I'll cut this as a breaking change just to make sure folks upgrade to Ansible 2.5 or higher. 

Just to check, are there any other changes that might be breaking you wanted to get in? I don't think there's any major issues with the 2.5 -> 2.6, and 2.6 -> 2.7 porting guides.

**Comment by michaelpporter** [comment]
I do not think so. I went though the playbook section of the changes searching code as I went. I believe I got them all.

**Comment by jaredledvina** [comment]
Sounds good, thanks again!

**Comment by jaredledvina** [comment]
Released in 4.0.0 🎉 
https://github.com/sensu/sensu-ansible/releases/tag/4.0.0

**Pull request merged**
