### PR TITLE
fix(issues) Attempt to address #16

### PR DESCRIPTION
**Pull request by michaelpporter**
This is an attempt at #16. It has breaking changes if merged due to the variables and group namges changing.

### CODE REVIEW

**Comment by michaelpporter** [comment]
I'm not sure if this is still needed. In hindsight it should have been with 4.0.0 to avoid a 5.0.0. ¯\\_(ツ)_/¯

**Review by jaredledvina — APPROVED** [review]
Yesssssssssssss!!! This looks good, thanks so much for knocking this out, I know that this involves editing a ton of places. No worries at all, cutting major releases isn't a pain and separating this out is probably going to be easiest for folks to upgrade to. 
👍 

EDIT:
> I'm not sure if this is still needed

I think this still makes complete sense to get merged in, as currently, some of the redis/rabbit variables can easily collide when you use another role, by namespacing them like this, it'll greatly help avoid that. This is also the approach I took with the WIP Sensu Go Ansible role I'm working on here: https://github.com/jaredledvina/sensu-go-ansible/blob/master/defaults/main.yml

**Comment by michaelpporter** [comment]
If you like i can update `uchiwa` as well.

**Comment by jaredledvina** [comment]
Hm @michaelpporter, perhaps I'm just blind, which `uchiwa` variables are you referring to? (Either way, it probably does make sense to make sure they are all prefixed in a semi-unique way for users). 

Also tagging @cjchand as he was interested in this work in the past as well.

**Comment by michaelpporter** [comment]
https://github.com/sensu/sensu-ansible/blob/6686137c490df4b889fab415072aae47e074b3b2/defaults/main.yml#L107

Agreed. I have sometime tonight (3 day weekend) I will get that changed.

**Comment by jaredledvina** [comment]
Ah, I see, so that it doesn't conflict with another Uchiwa role? i.e. prefix those w/ `sensu_` too?

**Comment by michaelpporter** [comment]
Right, almost done. just reviewing changes.

**Comment by jaredledvina** [comment]
Released in 5.0.0 https://github.com/sensu/sensu-ansible/releases/tag/5.0.0
🎉

**Pull request merged**
