### PR TITLE
Use 'include_tasks' for dynamic inclusions; The use of 'include' for …

### PR DESCRIPTION
**Pull request by charlez**
…tasks has been deprecated.

### CODE REVIEW

**Comment by jaredledvina** [comment]
Hey @charlez, I appreciate the PR, looking at the Ansible CHANGELOG, `include_task` is new to version 2.4. However, the current plan for this role is to maintain support for the last two major stable Ansible release as outlined here: https://github.com/sensu/sensu-ansible#ansible-version-support which matches the Ansible support setup on their end as well. 

So, I wouldn't be comfortable merging this until 2.5 is out and we officially drop support for Ansible 2.3. I think that might be next month-ish based on https://github.com/ansible/ansible/blob/devel/CHANGELOG.md#25-kashmir---march-2018-estimated. 

Does the above seem fair?

**Comment by charlez** [comment]
Deferring until dropping support for 2.3 (and 2.5 is out) is the correct decision.

**Comment by sorrowless** [comment]
@jaredledvina btw, Ansible 2.5 is out for about a month already ;)

**Comment by jaredledvina** [comment]
Just ten days since https://github.com/ansible/ansible/releases/tag/v2.5.0 but, yeah, I've been checking out http://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.5.html to see what we'll need to change (or so far, what we should change) to support 2.4 and 2.5 only. So far it's looking pretty good, I do need to run through the integration test setup and make sure that's testing for 2.5 now as well.

**Comment by jaredledvina** [comment]
Hi! I'm going to close this PR out for the time being but, linking it to https://github.com/sensu/sensu-ansible/issues/156 to ensure that once we find time to bump the minimum supported version of Ansible for this role and cut releases, we include this work.

**Pull request closed without merging**
