### PR TITLE
fix(group) rabbitmq_servers in default was not updated to new namespace.

### PR DESCRIPTION
**Pull request by michaelpporter**

### CODE REVIEW

**Review by jaredledvina — APPROVED** [review]

**Comment by jaredledvina** [comment]
Noting here, that it's interesting that the integration tests didn't fail without this. I probably need to dig some more and add additional tests to catch this type of failure in the future.

**Comment by michaelpporter** [comment]
```yaml
sensu_rabbitmq_server: true
```

Overrides 

```yaml
sensu_rabbitmq_host: "{{ groups['sensu_rabbitmq_servers'][0] }}"
```

Groups are not used in the testing it seems.

**Comment by jaredledvina** [comment]
Ahhhhhhh, makes sense, since we do the full integration test with just one container per Operating System.

**Comment by michaelpporter** [comment]
molecule.yaml

```yaml
 inventory:
    group_vars:
      all:
        sensu_master: true
        sensu_include_dashboard: true
        sensu_rabbitmq_server: true
        sensu_redis_server: true
        sensu_rabbitmq_host: "{{ ansible_hostname }}"
        sensu_redis_host: "{{ ansible_hostname }}"
        sensu_api_host: "{{ ansible_hostname }}"
        ansible_default_ipv4:
          address: 127.0.0.1
```

**Pull request merged**
