### PR TITLE
Add Amazon Linux AMI client side support.

### PR DESCRIPTION
**Pull request by abednarik**
This may help to the ones, like me, with client's using Amazon Linux AMI. didn't test the server side stuff like redis, rabbitmq or sensu components, but the client side stuff works great.

Thanks.

### CODE REVIEW

**Comment by smuth4** [comment]
Cool! I think you meant to copy vars/CentOS.yml instead of moving it though.

**Comment by abednarik** [comment]
You are right,  sorry.  Will fix that.

**Comment by abednarik** [comment]
Fixed.

Thanks.

**Comment by smuth4** [comment]
Thanks!

**Pull request merged**
